### ISSUE TITLE
Issue with closeTo() and text() predicates

### ISSUE THREAD

**Issue by nobal** [alp82/abmash#3]
I tried to get the texts near to a HtmlElement. It captures some but not all. I'm not sure whether it is a bug or maybe I'm not using the predicates properly. My html and java code are given below. 
## <b>HTML </b>

&lt;html&gt;
&lt;body&gt;
&lt;form&gt; 
&lt;label&gt; 
&lt;span style=&quot;font-size:large&quot;&gt;
Name&lt;span style=&quot;font-size:small&quot;&quot;&gt; type your name&lt;/span&gt;
&lt;/span&gt;
&lt;input type=&quot;text&quot; value=&quot;&quot; name=&quot;name&quot; &gt;
&lt;/label&gt;
&lt;/form&gt;
&lt;/body&gt;
&lt;/html&gt;
## <b>Java</b>

```
    HtmlElement me = browser.query(typable()).find().first();
    HtmlElements neighbors = browser.query(text(), closeTo(me))
            .find();
    System.out.println("Total texts around me: "+ neighbors.size());
    int i=1;
    for(HtmlElement e:neighbors){
        System.out.println(i+" "+e.getText());
        i++;
    }
```
## <b> Result</b>

Total texts around me: 1
1  type your name
## <b> Issue </b>

If you open the html code in browser, you see both the texts near to the input field. However, the java code finds only one text node near to the input field.  Specification says "closeTo(HtmlElement element)" finds elements visually close to the given HtmlElement, with a maximum distance of 300 pixels. The two texts are clearly within 300 pixels. Thus, is there any bug in this method  ?

Thanks

**Comment by alp82** [comment]
This is clearly a bug. I will look into this as soon as possible.

**Comment by nobal** [comment]
Thanks. I noticed that in my code above, if you put only text() predicate or only closeTo(me) predicate, you still get the same result i.e. the find() method returns HtmlElements of size 1. This observation might be helpful to figure out the bug...

**Comment by alp82** [comment]
I have a question concerning the expected result. You are right that the text "Name" does not appear in the result set, which should happen in some way. But, the whole text is contained in one element without seperation:

```
<span style="font-size:large">
    Name
    <span style="font-size:small""> type your name</span>
</span>
```

If you get the text for the inner span you will get "type your name". The outer span returns "Name type your name" (or at least it should after resolving this bug).

But i guess the result you wanted would be something like this:

```
1 Name
2 type your name
```

If that's the case, the HTML markup needs to be changed a little bit, so that the text "Name" is surrounded by its own tag:

```
<span style="font-size:large">
    <span>Name</span>
    <span style="font-size:small""> type your name</span>
</span>
```

Are my assumptions right and what do you think about it?

**Comment by nobal** [comment]
Based on the documentation, I expect two items in the result list as you guessed. Normally, I don't have right to change the HTML code of the page I'm working on. 

I was wondering whether you fixed this bug. If yes, please let me know the new version id.

**Comment by alp82** [comment]
You are right that changing the source code is mostly not an option. I fixed the bug, but i am not sure if you agree with the solution. Therefore i will wait with the new version number until you are ok with it.

Here is the current output of your code:

```
Total texts around me: 2
1  type your name
2 
            Name
             type your name
```

We have a semantical problem here. Let's assume we have html markup that is structured like this:

```
<div>
    There are <strong>3</strong> new messages
</div>
```

Now, there are technically two elements. The `<div>` and the `<strong>`. An alternative would be to automatically add "virtual" tags around the unmarked text bits like so:

```
<div>
    <span>There are</span> <strong>3</strong> <span>new messages</span>
</div>
```

Which would result in 4 elements: `<div>`, `<span>`, `<strong>` and a second `<span>`. I am not sure if that's the expected behavior in most cases.

The same applies to your html:

```
<span style="font-size:large">
    Name
    <span style="font-size:small""> type your name</span>
</span>
```

This returns the two `<span>` elements, but the text "Name" does not stand for itself. The first span contains the whole text "Name type your name" and the second the text of the inner span "type your name". It's difficult to tell if people would expect a separation of the text without markup ("Name") and the inner span ("type your name") when comparing the result to their visual perception of the page.

As you can see, i have a hard time on deciding which is the right way to go. But maybe you can tell me more about the task you want to achieve so that we can elaborate more on this problem.

**Comment by nobal** [comment]
Yes, this is tricky. I don't think adding extra tags would be a good idea. I wanted to get the visible label of the field I am interested in. That is, I want "Name type your name" as my label for the input tag in my html. So, using the current output of my code that you provided with the new changes, I can easily get that.

**Comment by alp82** [comment]
I incremented the version to `0.2.6-SNAPSHOT`. Feel free to test it and give feedback.
